ServiceName = "admin"
SymmetricKeyFile = "admin/certs/ofte_256bit_symmetric.key"
GeoIPDBFile = "admin/deploy/GeoLite2-City.mmdb"

[Server]
ListenAddr = ":8097"
ServiceMode = "debug"
Port = "65444"
CertFile = "/var/lib/ofte/cert.pem"
KeyFile = "/var/lib/ofte/key.pem"
StaticFilesLocation = "/Users/matthew/code/ofte/auth-service/src/ofte.io/services/admin/web-app"

[Server.CrossOrigin]
AllowAllOrigins = true
#AllowOrigins = ["https://foo.com:3000"]
AllowMethods = ["GET", "POST", "PUT", "HEAD", "DELETE"]
AllowHeaders = ["Origin", "Content-Length", "Content-Type"]
AllowCredentials = true
MaxAge = "12h"

[Database]
Database = "ofte"
Host = "localhost"
Port = 5432
User = "postgres"
Password = "devpassword"
SSLMode = "disable"
MaxConnections = 100
MaxIdleConnections = 50

[Store]
Endpoints = ["http://ETCD_HOST:2379"]
